/* Generated by `npm run visuals` (scripts/visuals.mjs). Do not edit. */

export interface ProjectVisuals {
  shots: string[];
  videos: string[];
  thumb?: string;
  /** File stems for the social cards, keyed by format; each is `<stem>-paper.png` / `<stem>-night.png`. */
  cards?: Partial<Record<'thumb' | 'og' | 'square' | 'story', string>>;
}

export const VISUALS: Record<string, ProjectVisuals> = {
  "home": {
    "shots": [],
    "videos": [],
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "intentional": {
    "shots": [],
    "videos": [],
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "rearranged": {
    "shots": [
      "lab",
      "loop"
    ],
    "videos": [],
    "thumb": "loop",
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "session-notes": {
    "shots": [
      "playground"
    ],
    "videos": [],
    "thumb": "playground",
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "stemscribe": {
    "shots": [
      "full",
      "loop"
    ],
    "videos": [],
    "thumb": "loop",
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "tabridge": {
    "shots": [
      "loop",
      "site"
    ],
    "videos": [],
    "thumb": "loop",
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "voxmpe": {
    "shots": [
      "loop",
      "studio"
    ],
    "videos": [],
    "thumb": "loop",
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  },
  "ysad": {
    "shots": [
      "circle",
      "loop"
    ],
    "videos": [],
    "thumb": "loop",
    "cards": {
      "thumb": "card-thumb",
      "og": "card-og",
      "square": "card-square",
      "story": "card-story"
    }
  }
};
